- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладка сервиса"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ version }}"
        networks:
          - name: "{{ network_name }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
  tags: "{{ name }}"