---
- name: Создание сети
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: Выкладка сервисов
  ansible.builtin.include_tasks: "../services/{{ item }}/service.yml"
  vars:
    name: "{{ item }}"
  loop: "{{ services }}"
