---
- name: Инициализация swarm
  community.docker.docker_swarm:
    advertise_addr: "{{ advertise_addr }}" # в какой сети будет работать swarm
    state: present
  register: token

- name: Наличие директории
  local_action:
    module: file
    path: ./tokens
    state: directory

- name: Сохранение токена manager
  local_action:
    module: copy
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"

- name: Сохранение токена worker
  local_action:
    module: copy
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
