---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладка сервиса"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            published_port: 3001
            target_port: 80
  tags: "{{ name }}"