---
- name: "[{{ name }}] Конфигурация конфига"
  block:
    - name: "[{{ name }}] Создание конфига"
      ansible.builtin.include_tasks: "../config-create.yml"
  tags: "{{ name }}"

  rescue:
    - name: "[{{ name }}] Удаление сервиса"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Создание конфига"
      ansible.builtin.include_tasks: "../config-create.yml"
