---
- name: "[{{ name }}] Создание конфига"
  vars:
    config_file: "{{ lookup('ansible.builtin.template', '{{ name }}/{{ config_item }}.j2') }}"
  community.docker.docker_config:
    name: "{{ config_item }}"
    data: "{{ config_file | b64encode }}"
    data_is_b64: true
    labels:
      config: "{{ config_file | hash('sha1') }}"
    state: present
