---
- name: "[{{ name }}] Конфигурация секрета"
  block:
    - name: "[{{ name }}] Создание секрета"
      ansible.builtin.include_tasks: "../secret-create.yml"
  tags: "{{ name }}"

  rescue:
    - name: "[{{ name }}] Удаление сервиса"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
    
    - name: "[{{ name }}] Создание секрета"
      ansible.builtin.include_tasks: "../secret-create.yml"