---
- name: "[{{ name }}] Создание секрета"
  vars:
      envFile: "{{ lookup('ansible.builtin.file', '{{ name }}/.env') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ envFile | b64encode }}"
    data_is_b64: true
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    state: present